version: '3.8'

services:

    splunk:
       image: splunk/splunk:8.1
       ports:
          - 8000:8000
          - 8089:8089
          - 9997:9997
       container_name: splunk_enterprise
       environment:
          SPLUNK_PASSWORD: martes1a
          SPLUNK_START_ARGS: --accept-license
       volumes:
          - ~/docker/splunk/etc
          - ~/docker/splunk/var
